spring:
  application:
    name: ms-entreprise

  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    ROOT: INFO




    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
