version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - GIT_REPO=file:///config-repo
    volumes:
      - ./config-repo:/config-repo



  discovery-server:
    build: ./Eureka_Discovery_Server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build: ./API_Gateway
    ports:
      - "8085:8085"
    depends_on:
      - discovery-server
      - config-server

  ms-employe:
    build: ./MS-Employe
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - config-server
      - discovery-server

  ms-entreprise:
    build: ./MS-Entreprise
    ports:
      - "9091:9091"
    depends_on:
      - mysql
      - config-server
      - discovery-server

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

