spring:
  application:
    name: ms-employe
  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    ROOT: INFO


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: employe-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
